//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCut.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class BarberDetail
    {
        public int BarberID { get; set; }
        
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [StringLength(50)]
        [Display(Name = "Hours of operation")]
        public string OperationHours { get; set; }

        [StringLength(50)]
        [Display(Name = "Weekly Schedule")]
        public string DaysOfWeek { get; set; }

        [StringLength(50)]
        [Display(Name = "Policy Information")]
        public string PolicyInfo { get; set; }
    
        public virtual Barber Barber { get; set; }
    }
}
