//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCut.UI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int RatingID { get; set; }
        public int BarberID { get; set; }
        public int ConsumerID { get; set; }
        public int RatingNumber { get; set; }
        public string Comments { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Consumer Consumer { get; set; }
    }
}
