//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCut.UI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Service
    {
        public int BarberID { get; set; }

        [StringLength(50)]
        [Display(Name = "Service Title")]
        public string ServiceTitle { get; set; }

        [StringLength(50)]
        [Display(Name = "Service Description")]
        public string ServiceDescription { get; set; }
    
        public virtual Barber Barber { get; set; }
    }
}
