//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickCutUI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rating
    {
        public int RatingID { get; set; }
        public int BarberID { get; set; }
        public int ConsumerID { get; set; }
        [Range(0, 5)]
        [Display(Name = "Rating")]
        public int RatingNumber { get; set; }
        [StringLength(500)]
        public string Comments { get; set; }
    
        public virtual Barber Barber { get; set; }
        public virtual Consumer Consumer { get; set; }
    }
}
